# Generated by Django 4.1.1 on 2022-10-03 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_booking_app', '0002_customeuser_address_customeuser_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='images',
            field=models.FileField(default=1, upload_to='', verbose_name='static/image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeuser',
            name='profile_image',
            field=models.FileField(default=1, upload_to='static/image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
