# Generated by Django 4.1.1 on 2022-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_booking_app', '0004_alter_customeuser_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='images',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='profile_image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
