# Generated by Django 4.1.1 on 2022-10-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_booking_app', '0009_alter_customeuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='profile_image',
            field=models.ImageField(upload_to='myProfiles'),
        ),
    ]
