# Generated by Django 4.1.1 on 2022-10-04 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_booking_app', '0010_alter_customeuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('Hotel_image', models.ImageField(upload_to='hotel')),
                ('rating', models.IntegerField(default=1)),
                ('hotel_info', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(default=100)),
                ('room_type', models.CharField(choices=[('AC', 'AC'), ('NON-AC', 'NON-AC')], default='NON-AC', max_length=20)),
                ('room_image', models.ImageField(upload_to='rooms')),
                ('room_price', models.FloatField()),
                ('room_availability', models.BooleanField()),
                ('room_info', models.CharField(max_length=500)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_booking_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(auto_now=True)),
                ('check_out', models.DateField()),
                ('Adult', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_booking_app.hotel')),
                ('select_room', models.ManyToManyField(to='Hotel_booking_app.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
