# Generated by Django 4.1.1 on 2022-10-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_booking_app', '0011_hotel_room_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='myProfiles'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='roll',
            field=models.CharField(choices=[('User', 'User'), ('Manager', 'Manager')], default='User', max_length=10),
        ),
    ]
