# Generated by Django 4.1.1 on 2022-10-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_booking_app', '0012_alter_customeuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
